Sourceforge [1733936] "phpdoc" does not return with error code "0" on success
git-svn-id: http://svn.php.net/repository/pear/packages/PhpDocumentor/trunk@238813 c90b9560-bf6c-de11-be94-00142212c4b1

diff --git a/phpdoc b/phpdoc
--- a/phpdoc
+++ b/phpdoc
@@ -2,7 +2,11 @@
 if [ -z "$PHP" ]; then
    PHP=`which php`
 fi
-(exec $PHP -C -q -d output_buffering=1 "$0" "$@") 2>/dev/null || echo "FAILED:  Bad environment variable \$PHP (set to \"$PHP\")" ; exit 1
+(exec $PHP -C -q -d output_buffering=1 "$0" "$@") 2>/dev/null
+if [ "$?" -ne "0" ]; then
+	echo "FAILED:  Bad environment variable \$PHP (set to \"$PHP\")"
+	exit 1
+fi
 <?php
 //
 // PhpDoc, a program for creating javadoc style documentation from php code
